### ISSUE TITLE
Add docker-compose/environment options to control Logging levels within alfresco

### ISSUE THREAD

**Issue by vierbergenlars** [xenit-eu/docker-alfresco#20]
In order to improve "on the fly" accessibility of logging levels, 

  *  with a form of persistence
  *   without having to hassle with file mounts

I request implementing a feature similar to the `GLOBAL_` parameters in the docker compose, to control the logging levels of alfresco:

example: `LOGGING_eu.xenit.apix.nodeservice=DEBUG` would result in at logging config line being written to `/usr/local/tomcat/shared/classes/alfresco/extension/custom-log4j.properties`  or the `dev-log4j.properties` at startup.

[From @RVanhuysseXenit [DOCKER-284](https://xenitsupport.jira.com/browse/DOCKER-284)]

**Comment by vierbergenlars** [comment]
You can write it to `${TOMCAT_DIR}/shared/classes/alfresco/extension/custom-log4j.properties`

**Comment by rschev** [comment]
For clarity: Should this only be able to set logger _levels_, i.e. things in the `log4j.logger` scope, or should this be a general translation layer to the options you can put in a log4j.properties file? Do we want that people are also able to set e.g. `log4j.appender.stdout.layout.ConversionPattern` with this system?

**Comment by AFaust** [comment]
From my Docker / customer experience, the requirement to configure a custom appender for certain loggers and additivity settings, even if only on-the-fly, quickly follows the ability to configure custom log levels, e.g. to avoid spamming the main log files with some env specific debug / trace logging. For that reason I directly implemented [a full translation of Log4J config in my Docker base images](https://github.com/Acosix/acosix-docker-alfresco/blob/master/basic-images/openjdk11-alfresco-repository/src/main/resources/initAlfresco.sh#L247).

**Comment by anghelutar** [comment]
If you are implementing this enhancement request, please make sure it's compatible with https://github.com/xenit-eu/docker-alfresco/pull/19 (for the case that PR gets merged).
