### ISSUE TITLE
Not possible to include own war

### ISSUE THREAD

**Issue by anghelutar** [xenit-eu/docker-alfresco#32]
PR https://github.com/xenit-eu/docker-alfresco/pull/28 breaks the possibility to include your own war file in the skeleton image. Due to the fact that /usr/local/tomcat/webapps/alfresco contains already one file, the new war is not expanded.

**Comment by vierbergenlars** [comment]
Using the `eu.xenit.docker-alfresco` gradle plugin, it is possible to include your own war file.
The plugin explodes the war by itself and inserts the expanded war into `/usr/local/tomcat/webapps/alfresco`, so it does not depend on tomcat to do the expansion when it first starts up.

Question: should we support other usages with our images or not?

**Comment by anghelutar** [comment]
> Using the `eu.xenit.docker-alfresco` gradle plugin, it is possible to include your own war file.
> The plugin explodes the war by itself and inserts the expanded war into `/usr/local/tomcat/webapps/alfresco`, so it does not depend on tomcat to do the expansion when it first starts up.
> 
> Question: should we support other usages with our images or not?

For one of the clients the war is built separately and simply added to the image via an ADD in the Dockerfile. A simple workaround (which I suggested for now) is to ADD the exploded war, then it works. I don't know if this is the correct solution.

**Comment by vierbergenlars** [comment]
An other relatively simple workaround that we can do is not to create the folder structure for the `log4j` file until we see a `LOG4J_` environment variable.

That way, custom wars lose the usage of `LOG4J_*` log configuration, but they can still be used like before.
