### ISSUE TITLE
Branch images should not be pushed to docker hub

### ISSUE THREAD

**Issue by anghelutar** [xenit-eu/docker-alfresco#57]
Only master and release branch(es) images should be pushed.
While this is true for enterprise images, it is not true for community images.

**Comment by kerkhofsd** [comment]
Given the current setup using GitHub Actions: 

```
    - name: Publish docker images
      if: ${{ startsWith(github.ref, 'refs/heads/master') || startsWith(github.ref, 'refs/heads/release') }}
```

This does not seem relevant anymore.
